source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'UNAlertView_Example', :exclusive => true do
  pod "UNAlertView", :path => "../"
end

target 'UNAlertView_Tests', :exclusive => true do
  pod "UNAlertView", :path => "../"

  
end
